"""Install/uninstall Tostr's "prefer Tostr for code navigation" guidance into the
config files of various coding agents (Claude Code, Cline, Cursor, …).

Design notes
------------
The *content* is ~identical across agents — the MCP tool names (`parse`, `skeleton`,
`search`, `inspect`) are the same in every client — so there is a single canonical body
(``templates/agent_context.md``) plus a thin per-agent ``AgentProfile`` that knows only
the things that actually differ: where the file lives, whether a global scope exists, and
the wrapper format (plain markdown vs Cursor's MDC frontmatter).

Shared config files (CLAUDE.md, .clinerules, …) commonly already contain the user's own
content, so we never clobber them: our text lives between managed markers and install is
an idempotent upsert of just that block (mirroring `_append_gitignore`). Dedicated files
that we own outright (Cursor's `tostr.mdc`) are written/removed wholesale.
"""
from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from tostr.exceptions import TostrError

# Managed-block markers. Anything between them is owned by Tostr and replaced on re-run;
# everything outside is the user's and left untouched.
BEGIN_MARKER = "<!-- BEGIN TOSTR (managed — regenerated by `tostr add-agent`; edits here are overwritten) -->"
END_MARKER = "<!-- END TOSTR (managed) -->"

# Cursor .mdc rule files carry YAML frontmatter; `alwaysApply: true` loads the rule into
# every request rather than gating it on a glob.
_MDC_FRONTMATTER = (
    "---\n"
    "description: Prefer Tostr (MCP) for code navigation, search, and dependency tracing\n"
    "alwaysApply: true\n"
    "---\n"
)


@dataclass(frozen=True)
class AgentProfile:
    """How one agent stores its system-prompt/rules config."""

    key: str  # CLI handle, e.g. "claude"
    label: str  # human name for messages
    project_path: str  # destination relative to the project root
    global_path: str | None = None  # ~-relative global destination, or None if unsupported
    fmt: str = "markdown"  # "markdown" | "mdc"
    dedicated: bool = False  # True = Tostr owns the whole file; False = inject a managed block


# Registry of supported agents. Most agents read plain markdown from a shared file, so the
# managed-block path covers them; Cursor is the one real format outlier (MDC frontmatter)
# and gets a dedicated file.
PROFILES: dict[str, AgentProfile] = {
    p.key: p
    for p in (
        AgentProfile("claude", "Claude Code", "CLAUDE.md", "~/.claude/CLAUDE.md"),
        AgentProfile("cline", "Cline", ".clinerules"),
        AgentProfile("copilot", "GitHub Copilot", ".github/copilot-instructions.md"),
        AgentProfile("codex", "Codex / AGENTS.md", "AGENTS.md", "~/.codex/AGENTS.md"),
        AgentProfile(
            "cursor",
            "Cursor",
            ".cursor/rules/tostr.mdc",
            fmt="mdc",
            dedicated=True,
        ),
    )
}


def _read_template(name: str) -> str:
    """Read a bundled scaffold from `tostr/templates/`."""
    return resources.files("tostr.templates").joinpath(name).read_text(encoding="utf-8")


def _render_body(profile: AgentProfile) -> str:
    """The canonical guidance, wrapped for the target format."""
    body = _read_template("agent_context.md").strip()
    if profile.fmt == "mdc":
        return f"{_MDC_FRONTMATTER}\n{body}\n"
    return body + "\n"


def _resolve(agent_key: str) -> AgentProfile:
    try:
        return PROFILES[agent_key.lower()]
    except KeyError:
        supported = ", ".join(sorted(PROFILES))
        raise TostrError(f"Unknown agent '{agent_key}'. Supported: {supported}.")


def _destination(profile: AgentProfile, target_path: Path, scope: str) -> Path:
    if scope == "global":
        if not profile.global_path:
            raise TostrError(
                f"{profile.label} has no global config location; install it per-project "
                f"(drop --global)."
            )
        return Path(profile.global_path).expanduser()
    return target_path / profile.project_path


def _upsert_block(content: str, body: str) -> str:
    """Insert or replace the managed block in `content`, preserving surrounding text."""
    block = f"{BEGIN_MARKER}\n{body.strip()}\n{END_MARKER}"
    if BEGIN_MARKER in content and END_MARKER in content:
        pre = content.split(BEGIN_MARKER, 1)[0].rstrip()
        post = content.split(END_MARKER, 1)[1].lstrip("\n")
        parts = [pre, block, post]
    else:
        parts = [content.rstrip(), block]
    joined = "\n\n".join(p for p in parts if p).rstrip()
    return joined + "\n"


def _strip_block(content: str) -> str:
    """Remove the managed block, leaving the user's surrounding text intact."""
    if BEGIN_MARKER not in content or END_MARKER not in content:
        return content
    pre = content.split(BEGIN_MARKER, 1)[0].rstrip()
    post = content.split(END_MARKER, 1)[1].lstrip("\n")
    joined = "\n\n".join(p for p in (pre, post) if p).rstrip()
    return joined + "\n" if joined else ""


def add_agent(
    agent_key: str,
    target_path: Path,
    scope: str = "project",
    force: bool = False,
) -> list[str]:
    """Install Tostr guidance into an agent's config. Idempotent and non-destructive:
    shared files get the managed block upserted (user content preserved); the dedicated
    Cursor file is created (or overwritten only with `force` if it lacks our markers).
    Returns human-readable report lines."""
    profile = _resolve(agent_key)
    dest = _destination(profile, target_path, scope)
    body = _render_body(profile)

    dest.parent.mkdir(parents=True, exist_ok=True)
    existed = dest.exists()

    if profile.dedicated:
        if existed and force is False and BEGIN_MARKER not in dest.read_text():
            return [
                f"Skipped {dest} ({profile.label} file exists and isn't Tostr-managed; "
                f"use --force to overwrite)."
            ]
        # We own this file: frontmatter + a managed block (so re-runs and removal are uniform).
        dest.write_text(_upsert_block(body if not existed else dest.read_text(), body))
        verb = "Updated" if existed else "Created"
        return [f"{verb} {dest} ({profile.label})."]

    content = dest.read_text() if existed else ""
    updated = _upsert_block(content, body)
    if existed and updated == content:
        return [f"{dest} already up to date ({profile.label})."]
    dest.write_text(updated)
    verb = "Updated" if existed else "Created"
    return [f"{verb} {dest} ({profile.label})."]


def remove_agent(agent_key: str, target_path: Path, scope: str = "project") -> list[str]:
    """Uninstall Tostr guidance. Strips the managed block from shared files (deleting the
    file if it becomes empty) and deletes the dedicated Cursor file outright."""
    profile = _resolve(agent_key)
    dest = _destination(profile, target_path, scope)

    if not dest.exists():
        return [f"Nothing to remove at {dest} ({profile.label})."]

    if profile.dedicated:
        dest.unlink()
        return [f"Removed {dest} ({profile.label})."]

    content = dest.read_text()
    if BEGIN_MARKER not in content:
        return [f"No Tostr block in {dest} ({profile.label}); left it untouched."]
    stripped = _strip_block(content)
    if stripped.strip():
        dest.write_text(stripped)
        return [f"Removed Tostr block from {dest} ({profile.label})."]
    dest.unlink()
    return [f"Removed Tostr block and deleted now-empty {dest} ({profile.label})."]


def list_agents() -> list[str]:
    """Report lines describing the supported agents and where they install."""
    lines = []
    for p in PROFILES.values():
        scopes = "project" + (", global" if p.global_path else "")
        lines.append(f"{p.key:<9} {p.label:<20} → {p.project_path}  [{scopes}]")
    return lines
